In [1]:
import cv2
import scipy.io as sio
import os
import math
import numpy as np
import pandas as pd
import io
from PIL import Image
import copy
import argparse
import matplotlib.pyplot as plt
import matplotlib.image as mpim

from pathlib import Path
from natsort import natsorted
import glob

In [2]:
root_dir = Path(os.getcwd()).parent
print(f"Root Dir: {root_dir}")

Root Dir: /Users/hari/JKU/cv/compute_vision


In [3]:
video_dir = os.path.join(root_dir, "data/frame_not_annotated/")
print(video_dir)

/Users/hari/JKU/cv/compute_vision/data/frame_not_annotated/


In [4]:
class GetVideoFrame():
    def __init__(self, image_folder):
        self.image_frames = natsorted(glob.glob(os.path.join(image_folder, "*")))

    @staticmethod
    def open_image(img_path):
        img = Image.open(img_path)
        return img

    def __getitem__(self, item):
        image_list = natsorted(glob.glob(os.path.join(self.image_frames[item], "*.png")))
        img_arr = [self.open_image(i) for i in image_list]
        return np.stack(img_arr ,axis=0)

In [5]:
data = GetVideoFrame(video_dir)
for i in data:
    print(i[0])
    break

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[102 102 102]
  [ 91  91  91]
  [ 97  97  97]
  ...
  [ 30  30  30]
  [ 26  26  26]
  [ 27  27  27]]

 [[ 69  69  69]
  [ 55  55  55]
  [ 59  59  59]
  ...
  [ 31  31  31]
  [ 33  33  33]
  [ 33  33  33]]

 [[ 70  70  70]
  [ 58  58  58]
  [ 65  65  65]
  ...
  [ 25  25  25]
  [ 24  24  24]
  [ 19  19  19]]]


In [6]:
while True:
    x = np.array(i[0])
    cv2.imshow('gray', x)
    if cv2.waitKey(25) & 0xFF == ord('q'):
          break