In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
cap = cv2.VideoCapture('video_000.mp4')
 
# Check if camera opened successfully
if (cap.isOpened()== False): 
  print("Error opening video stream or file")
 
# Read until video is completed
while(cap.isOpened()):
  # Capture frame-by-frame
  ret, frame = cap.read()
  if ret == True:
 
    # Display the resulting frame
    
    frame = cv2.GaussianBlur(frame,(3,3),0)
    frame = cv2.Laplacian(frame,cv2.CV_64F)
    cv2.imshow('Frame',frame)
 
    # Press Q on keyboard to  exit
    if cv2.waitKey(25) & 0xFF == ord('q'):
      break
 
  # Break the loop
  else: 
    break
 
# When everything done, release the video capture object
cap.release()
 
# Closes all the frames
cv2.destroyAllWindows()


In [5]:



cv2.imshow('frame',img)
cv2.waitKey()

-1

In [3]:
print(img)

[[21 18 25 ... 13 14 18]
 [22 20 18 ... 16 15 14]
 [18 20 12 ... 16 15 14]
 ...
 [17 17 18 ... 19 21 13]
 [18 19 14 ... 19 18 18]
 [17 16 18 ... 19 18 18]]
